# Generated by Django 6.0.6 on 2026-06-24 14:16

import django.utils.timezone
import filesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[filesapp.models.validate_file]),
        ),
    ]
